# Puerto del ms
server:
  port: 8888

# Config server
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL:https://github.com/yisasthemanuel/config-repo.git}
          username: ${CONFIG_REPO_USER:yisasthemanuel}
          password: ${CONFIG_REPO_PASSWORD:Calendula009$}
          skip-ssl-validation: true
          
# Seguridad para acceder al config server. Se utiliza el mecanismo simple de usuario/clave
  security:
    user:
      name: root
      password: s3cr3t

# ACTUATOR - PROMETHEUS
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true 